import {IConformance, Conformance}  from '../resources/Conformance';
import {Enforce}                    from 'ts-objectschema';

/**
 * Manage every resource in the application
 */
export class ConformanceManager {
    /**
     * Instanceiated conformance resource
     */
    public conformance: Conformance;
    /**
     * Add some of the autogenerated conformance fields to the conformance
     * @param   {IConformance}  conformance     conformance that needs the fields added
     * @returns {Void}
     */
    public addAutoConformance(conformance: IConformance): void {

        // see conformance for what fields to add here
    }
    /**
     * Build the conformance
     * @param   {IConformance}  conformance     conformance to be builded
     * @returns {Void}
     */
    public buildConformance(conformance: IConformance): void {
        
        // some more fields should be added to the conformance here

        this.conformance = new Conformance(conformance, Enforce.required);
    }
}
